Repository cdk8s-team/cdk8s, pull requests merged in 2021-06, with the labels that each got.

#598 chore(deps): upgrade projen
  .github/pull_request_template.md
  .projen/deps.json
  package.json
  yarn.lock
Labels: auto-merge

#601 chore(deps): upgrade projen
  .gitattributes
  .github/workflows/upgrade-dependencies.yml
  .github/workflows/upgrade-projen.yml
  .mergify.yml
  .projen/deps.json
  .projen/tasks.json
  package.json
  yarn.lock
Labels: auto-merge

#610 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#611 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#612 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#613 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#614 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#530 chore: add helm-bitnami examples
  examples/java/helm-bitnami/.gitignore
  examples/java/helm-bitnami/README.md
  examples/java/helm-bitnami/cdk8s.yaml
  examples/java/helm-bitnami/package.json
  examples/java/helm-bitnami/pom.xml
  examples/java/helm-bitnami/src/main/java/com/mycompany/app/HelmBitnami.java
  examples/python/helm-bitnami/.gitignore
  examples/python/helm-bitnami/Pipfile
  examples/python/helm-bitnami/README.md
  examples/python/helm-bitnami/cdk8s.yaml
  examples/python/helm-bitnami/main.py
  examples/python/helm-bitnami/package.json
  examples/typescript/helm-bitnami/.gitignore
  examples/typescript/helm-bitnami/README.md
  examples/typescript/helm-bitnami/cdk8s.yaml
  examples/typescript/helm-bitnami/index.ts
  examples/typescript/helm-bitnami/package.json
  examples/typescript/helm-bitnami/tsconfig.json
Labels: response-requested

#617 chore: update organization URL path to cdk8s-team
  CONTRIBUTING.md
  README.md
  docs/concepts/escape-hatches.md
  docs/examples/crd.md
  docs/examples/hello.md
  docs/examples/plus-elasticsearch.md
  docs/examples/plus-ingress.md
  docs/examples/podinfo.md
  docs/examples/web-service.md
  docs/support.md
  examples/typescript/cdk8s-plus-elasticsearch-query/README.md
  mkdocs.yml
  research/README.md
  website/layouts/index.html
Labels: contribution/core
