Repository cdk8s-team/cdk8s, pull requests merged in 2022-10, with the labels that each got.

#998 chore(deps): upgrade dependencies
  .npmignore
  package.json
  test/test-go-app/expected/construct-metadata.json
  test/test-java-app/expected/construct-metadata.json
  test/test-python-app/expected/construct-metadata.json
  test/test-typescript-app/expected/construct-metadata.json
  yarn.lock
Labels: auto-approve

#999 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1000 chore(deps): upgrade dependencies
  .github/workflows/build.yml
  .github/workflows/upgrade.yml
  package.json
  yarn.lock
Labels: auto-approve

#1002 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1003 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1004 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1008 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1009 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1010 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1011 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1012 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1013 chore(deps): upgrade dependencies
  .projen/deps.json
  package.json
  yarn.lock
Labels: auto-approve

#1014 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1015 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1017 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1018 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1020 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1021 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#987 chore(docs): website development README
  docs/README.md
Labels: documentation, website

#1022 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1025 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1026 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1027 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1028 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1033 chore(deps): upgrade dependencies
  .github/workflows/build.yml
  .github/workflows/upgrade.yml
  package.json
  yarn.lock
Labels: auto-approve

#1036 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1041 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1043 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1044 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1046 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1048 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1049 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1045 fix(website): improved SEO management
  docs/build.sh
  docs/requirements.txt
  mkdocs.yml
  website/.gitignore
  website/config.yaml
  website/layouts/index.html
  website/layouts/sitemap.xml
  website/static/robots.txt
  website/static/sitemap-root.xml
Labels: website
